version: '3.3'
services:
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: rusprofileservice
    ports:
      - "8001:8080"
    volumes:
      - ./swagger:/usr/share/nginx/html/swagger
    environment:
      API_URL: swagger/RusprofileGrpc.swagger.json